{{- range $config := .Values.configMaps }}
#Adding the details of CCM
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $config.name }}
{{- with $config.envVars }}
data:
{{- toYaml . | nindent 2 }}
{{- end }}
---
{{- end }}