{{- if .Values.properties.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "yantra-oms.serviceAccountName" . }}
  labels:
    {{- include "yantra-oms.labels" . | nindent 4 }}
  {{- with .Values.properties.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}

